### ISSUE TITLE
how to use SSL certs?

### ISSUE THREAD

**Issue by dragonballa** [nwutils/nw-local-server-example#1]
I am using your repo to load an iframe that tries to load https://asdf.com

The problem is that it throws net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH 

I created a self signed .crt and .key but don't know where to add this

I see a folder for /certs exist, not sure what the format should be.

Please see : https://stackoverflow.com/questions/68966375/nw-js-iframe-fails-to-load-some-https-website-due-to-neterr-ssl-version-or-cip

**Comment by TheJaredWilcurt** [comment]
There seem to be several issues around iframes on the NW.js board,

* https://github.com/nwjs/nw.js/issues?q=is%3Aissue+is%3Aopen+iframe

Some have labels applied (meaning they've been looked at/confirmed as happening), many look related, some have Roger self-assigned, meaning he is looking into them. This is likely a bug that will be fixed soon upstream. Closing, and redirecting there.
